# Dependabot will run on day 27 of each month at 03:24 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "24 3 27 * *"
    open-pull-requests-limit: 20
    assignees:
      - "BenAhrdt"
    versioning-strategy: "increase"
